package com.mycompany.view;

import com.mycompany.controller.ClienteController;
import com.mycompany.model.entities.Cliente;
import com.mycompany.services.ClienteService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lombok.Data;

import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import listeners.CustomRenderer;
import listeners.SelectionListener;
/**
 *
 * @author bravo
 */
@Data
public class ClientesTable extends javax.swing.JFrame {

    ClienteController cController = new ClienteController(new ClienteService());
    DefaultTableModel dtmClientes = new DefaultTableModel();

    private JFrame previousFrame;

    /**
     * Creates new form ClientesTable
     */
    public ClientesTable() {
        initComponents();
        this.setLocationRelativeTo(null); /*centrar formulario*/
        loadCboClientes();
        loadColumns();
        loadRows();
        setupSelectionListener();
    }

    public void loadColumns() {
        dtmClientes.addColumn("Id");
        dtmClientes.addColumn("Nombre");
        dtmClientes.addColumn("Apellido");
        dtmClientes.addColumn("Dni");
        dtmClientes.addColumn("Teléfono");
        dtmClientes.addColumn("Dirección");
        tbClientes.setModel(dtmClientes);
    }

    public void loadRows() {
        List<Cliente>  lstClientes = cController.getEmployees();
        dtmClientes.setRowCount(0);
        for (Cliente c : lstClientes) {
            Object[] vec = new Object[6];
            vec[0] = c.getIdCliente();
            vec[1] = c.getNombre();
            vec[2] = c.getApellido();
            vec[3] = c.getDni();
            vec[4] = c.getTelefono();
            vec[5] = c.getDireccion();
            dtmClientes.addRow(vec);
        }
        tbClientes.setModel(dtmClientes);
    }
    
    public void loadCboClientes(){
        List<Cliente> lstClientes = cController.getEmployees();
        DefaultComboBoxModel dcbmCliente = new DefaultComboBoxModel();
        dcbmCliente.addElement("[0] - All");
        for(Cliente c : lstClientes){
            String cliente = "[" + c.getIdCliente() + "] - " + c.getNombre() + " " + c.getApellido();
            dcbmCliente.addElement(cliente);
        }
        cboClientes.setModel(dcbmCliente);
        cboEditCliente.setModel(dcbmCliente);
    }
    
     public void setupSelectionListener() {
        ListSelectionModel selectionModel = tbClientes.getSelectionModel();
        selectionModel.addListSelectionListener(new SelectionListener(tbClientes));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewForm = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        txtNewNombre = new javax.swing.JTextField();
        btnNewSave = new javax.swing.JButton();
        btnNewRestore = new javax.swing.JButton();
        btnNewCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNewApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNewDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNewTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNewDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EditForm = new javax.swing.JFrame();
        btnEditSave = new javax.swing.JButton();
        btnEditRestore = new javax.swing.JButton();
        btnEditCancel = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cboEditCliente = new javax.swing.JComboBox<>();
        txtEditDireccion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEditApellido = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtEditDNI = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEditTelefono = new javax.swing.JTextField();
        txtEditNombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cboClientes = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnDeleteCliente = new javax.swing.JButton();
        btnEditCliente = new javax.swing.JButton();
        btnNewCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        NewForm.setSize(new java.awt.Dimension(300, 350));

        btnNewSave.setText("Guardar Cliente");
        btnNewSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewSaveActionPerformed(evt);
            }
        });

        btnNewRestore.setText("Restablecer");
        btnNewRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRestoreActionPerformed(evt);
            }
        });

        btnNewCancel.setText("Cancelar");
        btnNewCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCancelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NUEVO CLIENTE");

        jLabel5.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("DNI*");

        jLabel10.setText("Teléfono*");

        jLabel11.setText("Dirección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(btnNewRestore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewNombre)
                            .addComponent(txtNewApellido)
                            .addComponent(txtNewDNI)
                            .addComponent(txtNewTelefono)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewDireccion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNewNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNewApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNewDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNewTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNewDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewRestore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewFormLayout = new javax.swing.GroupLayout(NewForm.getContentPane());
        NewForm.getContentPane().setLayout(NewFormLayout);
        NewFormLayout.setHorizontalGroup(
            NewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewFormLayout.setVerticalGroup(
            NewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        EditForm.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        EditForm.setSize(new java.awt.Dimension(300, 400));

        btnEditSave.setText("Actualizar Cliente");
        btnEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaveActionPerformed(evt);
            }
        });

        btnEditRestore.setText("Restablecer");
        btnEditRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRestoreActionPerformed(evt);
            }
        });

        btnEditCancel.setText("Cancelar");
        btnEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCancelActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MODIFICAR CLIENTE");

        jLabel15.setText("Clientes");

        cboEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEditClienteActionPerformed(evt);
            }
        });

        jLabel17.setText("Dirección");

        jLabel6.setText("Nombre");

        jLabel18.setText("Apellido");

        jLabel19.setText("DNI*");

        jLabel20.setText("Teléfono*");

        javax.swing.GroupLayout EditFormLayout = new javax.swing.GroupLayout(EditForm.getContentPane());
        EditForm.getContentPane().setLayout(EditFormLayout);
        EditFormLayout.setHorizontalGroup(
            EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(btnEditSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditRestore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EditFormLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboEditCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditFormLayout.createSequentialGroup()
                        .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditNombre)
                            .addComponent(txtEditApellido)
                            .addComponent(txtEditDNI)
                            .addComponent(txtEditTelefono)))
                    .addGroup(EditFormLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEditDireccion)))
                .addContainerGap())
        );
        EditFormLayout.setVerticalGroup(
            EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cboEditCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEditApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtEditDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtEditTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEditDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRestore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 240, 213));

        jLabel12.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\cliente.png")); // NOI18N
        jLabel12.setText("CLIENTES");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel13.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel13.setText("Buscar Cliente");

        txtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscarCaretUpdate(evt);
            }
        });

        cboClientes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClientesActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 153, 0));
        btnBack.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\regres.png")); // NOI18N
        btnBack.setText("Volver");
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDeleteCliente.setBackground(new java.awt.Color(255, 153, 0));
        btnDeleteCliente.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        btnDeleteCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCliente.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\elimi.png")); // NOI18N
        btnDeleteCliente.setText("Eliminar");
        btnDeleteCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDeleteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClienteActionPerformed(evt);
            }
        });

        btnEditCliente.setBackground(new java.awt.Color(255, 153, 0));
        btnEditCliente.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnEditCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCliente.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\modi.png")); // NOI18N
        btnEditCliente.setText("Modificar Existente");
        btnEditCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClienteActionPerformed(evt);
            }
        });

        btnNewCliente.setBackground(new java.awt.Color(255, 153, 0));
        btnNewCliente.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnNewCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNewCliente.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\regi.png")); // NOI18N
        btnNewCliente.setText("Registrar Nuevo");
        btnNewCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNewCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClienteActionPerformed(evt);
            }
        });

        tbClientes.setAutoCreateRowSorter(true);
        tbClientes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbClientes.setForeground(new java.awt.Color(153, 51, 0));
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbClientes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tbClientes);

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\deco.png")); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\WorkSpace\\ProjectTheta\\ProjectTheta\\src\\main\\java\\img\\deco.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnNewCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBuscar))))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSaveActionPerformed
        if(getNewDni().isBlank()
              ||getNewTelefono().isBlank()){
            JOptionPane.showMessageDialog(this, "Error, debe llenar todas las casillas", "Casillas sin llenar", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(datosRegistrados(getNewDni(), getNewTelefono(), 0)) { return; }
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que desea generar el nuevo cliente?");
        if(resp!=0){ return; }
        Cliente temp = new Cliente(0, getNewNombre(), getNewApellido(), getNewDni(), getNewTelefono(), getNewDireccion());
        cController.addCustomer(temp);
    }//GEN-LAST:event_btnNewSaveActionPerformed

    private void btnNewRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRestoreActionPerformed
        txtNewNombre.setText("");
        txtNewApellido.setText("");
        txtNewDNI.setText("");
        txtNewTelefono.setText("");
        txtNewDireccion.setText("");
    }//GEN-LAST:event_btnNewRestoreActionPerformed

    private void btnNewCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCancelActionPerformed
        loadRows();
        loadCboClientes();
        NewForm.dispose();
    }//GEN-LAST:event_btnNewCancelActionPerformed

    private void btnEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaveActionPerformed
        if(getEditDni().isBlank()
              ||getEditTelefono().isBlank()){
            JOptionPane.showMessageDialog(this, "Error, debe llenar todas las casillas", "Casillas vacias", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(datosRegistrados(getEditDni(), getEditTelefono(), getSelectedClienteEdit())) { return; }
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que desea editar el Cliente? Esta acción es Irreversible");
        if (resp != 0) { return; }
        Cliente temp = new Cliente(getSelectedClienteEdit(), getEditNombre(), getEditApellido(), getEditDni(), getEditTelefono(), getEditDireccion());
        cController.updateCustomer(temp);
        loadCboClientes();
        cboClientes.setSelectedIndex(0);
        llenarDatosEdit();
    }//GEN-LAST:event_btnEditSaveActionPerformed

    private void btnEditRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRestoreActionPerformed
        llenarDatosEdit();
    }//GEN-LAST:event_btnEditRestoreActionPerformed

    private void btnEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCancelActionPerformed
        loadRows();
        loadCboClientes();
        EditForm.dispose();
    }//GEN-LAST:event_btnEditCancelActionPerformed

    private void cboEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEditClienteActionPerformed
        llenarDatosEdit();
    }//GEN-LAST:event_cboEditClienteActionPerformed

    private void txtBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarCaretUpdate
        DefaultComboBoxModel<String> dcbmClientes = new DefaultComboBoxModel<>();
        loadCboClientes();
        String busqueda = txtBuscar.getText();
        for(int i=0;i<cboClientes.getItemCount();i++){
            String item = cboClientes.getItemAt(i);
            if(item.toLowerCase().contains(busqueda.toLowerCase())){
                dcbmClientes.addElement(item);
            }
        }
        dcbmClientes.addElement("[0] - All");
        cboClientes.setModel(dcbmClientes);
    }//GEN-LAST:event_txtBuscarCaretUpdate

    private void cboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClientesActionPerformed
        if(getSelectedCliente()==0) {
            loadRows();
            return;
        }
        Cliente temp = cController.findCustomerById(getSelectedCliente());
        dtmClientes.setRowCount(0);
        Object[] vec = new Object[6];
        vec[0] = temp.getIdCliente();
        vec[1] = temp.getNombre();
        vec[2] = temp.getApellido();
        vec[3] = temp.getDni();
        vec[4] = temp.getTelefono();
        vec[5] = temp.getDireccion();
        dtmClientes.addRow(vec);
        tbClientes.setModel(dtmClientes);
    }//GEN-LAST:event_cboClientesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        previousFrame.setVisible(true);
        if(RegistrarPedido.class.isInstance(previousFrame)){
            RegistrarPedido obj=(RegistrarPedido)previousFrame;
            obj.updateCbos();
        }
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClienteActionPerformed
        Cliente temp = cController.findCustomerById(getSelectedCliente());
        if(getSelectedCliente()==0)
        {
            JOptionPane.showMessageDialog(this, "Error, aun no selecciona un cliente", "Cliente sin seleccionar", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar al Cliente "+temp.getNombre()+" "+temp.getApellido()+"? Esta acción es Irreversible");
        if (resp != 0) { return; }
        cController.deleteCustomer(temp);
        loadRows();
        loadCboClientes();
    }//GEN-LAST:event_btnDeleteClienteActionPerformed

    private void btnEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClienteActionPerformed
        if(cController.getEmployees().isEmpty()){
            JOptionPane.showMessageDialog(this, "Aún no hay clientes registrados", "Sin clientes", JOptionPane.WARNING_MESSAGE);
            return;
        }
        EditForm.setVisible(true);
    }//GEN-LAST:event_btnEditClienteActionPerformed

    private void btnNewClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClienteActionPerformed
        NewForm.setVisible(true);
    }//GEN-LAST:event_btnNewClienteActionPerformed

    private String getNewNombre()    { return txtNewNombre.getText();    }
    private String getNewApellido()  { return txtNewApellido.getText();  }
    private String getNewDni()       { return txtNewDNI.getText();       }
    private String getNewTelefono()  { return txtNewTelefono.getText();  }
    private String getNewDireccion() { return txtNewDireccion.getText(); }
    
    private String getEditNombre()   { return txtEditNombre.getText();   }
    private String getEditApellido() { return txtEditApellido.getText(); }
    private String getEditDni()      { return txtEditDNI.getText();      }
    private String getEditTelefono() { return txtEditTelefono.getText(); }
    private String getEditDireccion(){ return txtEditDireccion.getText();}
    
    private int getSelectedClienteEdit(){
        if(cboEditCliente.getItemCount()==0) { return 1; }
        String  palabra = cboEditCliente.getSelectedItem().toString();
        int     indice  = palabra.indexOf(']');
        return Integer.parseInt(palabra.substring(1, indice));
    }
    private int getSelectedCliente(){
        if(cboClientes.getItemCount()==0){ return 0; }
        String  palabra = cboClientes.getSelectedItem().toString();
        int     indice = palabra.indexOf(']');
        return Integer.parseInt(palabra.substring(1, indice));
    }
    private boolean datosRegistrados(String dni, String telefono, int id){
        switch (cController.datosExist(dni, telefono, id)){
            case 1:
                JOptionPane.showMessageDialog(this, "Error, El dni ingresado ya se encuentra registrado", "Dato ya registrado", JOptionPane.WARNING_MESSAGE);
                return true;
            case 2:
                JOptionPane.showMessageDialog(this, "Error, El telefono ingresado ya se encuentra registrado", "Dato ya registrado", JOptionPane.WARNING_MESSAGE);
                return true;
            default:
                return false;
        }
    }
    private void llenarDatosEdit(){
        Cliente temp = new Cliente(0, "", "", "", "", "");
        if(getSelectedClienteEdit() != 0){ temp = cController.findCustomerById(getSelectedClienteEdit()); }
        txtEditNombre.setText(temp.getNombre());
        txtEditApellido.setText(temp.getApellido());
        txtEditDNI.setText(temp.getDni());
        txtEditTelefono.setText(temp.getTelefono());
        txtEditDireccion.setText(temp.getDireccion());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame EditForm;
    private javax.swing.JFrame NewForm;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCliente;
    private javax.swing.JButton btnEditCancel;
    private javax.swing.JButton btnEditCliente;
    private javax.swing.JButton btnEditRestore;
    private javax.swing.JButton btnEditSave;
    private javax.swing.JButton btnNewCancel;
    private javax.swing.JButton btnNewCliente;
    private javax.swing.JButton btnNewRestore;
    private javax.swing.JButton btnNewSave;
    private javax.swing.JComboBox<String> cboClientes;
    private javax.swing.JComboBox<String> cboEditCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEditApellido;
    private javax.swing.JTextField txtEditDNI;
    private javax.swing.JTextField txtEditDireccion;
    private javax.swing.JTextField txtEditNombre;
    private javax.swing.JTextField txtEditTelefono;
    private javax.swing.JTextField txtNewApellido;
    private javax.swing.JTextField txtNewDNI;
    private javax.swing.JTextField txtNewDireccion;
    private javax.swing.JTextField txtNewNombre;
    private javax.swing.JTextField txtNewTelefono;
    // End of variables declaration//GEN-END:variables
}
